### ISSUE TITLE
Charts in local time

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#102]
reported by @Ryton

**Comment by JrtPec** [comment]
The problem with this is that, technically, from the data we don't know in which timezone a fluksometer is located. All data is in UTC.

We could however by default assume they are all located in Belgium, or, ideally, have a `timezone` field in the Houseprint.

I recon the best place to put a localisation function is right in the `get_data` method in the Houseprint, by having a flag `localised (or localized?) = True` (British vs American spelling, Pandas uses `localize` I think.

**Comment by saroele** [comment]
Currently, all charts on www.opengrid.be are in localtime, supposing all data comes from the Europe/Brussels time zone.  As JrtPec proposes, we can include a timezone field in the houseprint, obtained from country or zip code.  Not a priority now.
