### ISSUE TITLE
Error when running sync_tempos()

### ISSUE THREAD

**Issue by WolfBerwouts** [opengridcc/opengrid#144]
Someone experiencing the same error when running electricity_standy?

<img width="1131" alt="screen shot 2016-06-30 at 10 28 19" src="https://cloud.githubusercontent.com/assets/12158812/16481875/a55d144c-3ead-11e6-8360-61d4351afb39.png">

**Comment by JrtPec** [comment]
This is an issue with tmpo, not OpenGrid. Not really an error, but a warning that has to do with the way Flukso signs its certificates. I'm sure Bart knows about it, but you could remind him by opening an issue on Flukso/tmpo-py.

There is nothing we can do about it over here, so I'm closing this. You can safely ignore the warnings.
