### ISSUE TITLE
Update server: opengrid and website

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/opengrid#160]
If I understand it correctly, the server currently runs OpenGrid via pip, not via git anymore?

In order to test the Slackbot on the website, following steps are needed:

- [x] Update the pip package on pypi
- [x] Update the package on the server
- [x] Pull the latest version of the website on the server
- [x] Manually change Slackbot config stuff on the server
- [x] Restart the web server (`sudo service uwsgi restart opengrid` or something)

@saroele could you answer the first question? If so, could you take care of the first 2 steps?

**Comment by saroele** [comment]
Indeed, it's to be sure we run a specific release.
I have some maintenance work to do.  I plan to do that in the coming days.

thanks for your work!
roel

**Comment by JrtPec** [comment]
Don't forget the version bump!

**Comment by saroele** [comment]
the coming days passed too quickly for me, but tomorrow evening seems like more than enough to get this done.
