### ISSUE TITLE
timeseries.interpolate trows "Unbounded" error

### ISSUE THREAD

**Issue by Ryton** [opengridcc/opengrid#22]
See documented case in  WIP OGRE - Piecharts_water_v0.7, 
(cell with saroele's sample code) gives errors (on windows 8 machine/+winpython) on *.interpolate:

<code>
--------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-11-23e7a79e7a04> in <module>()
     16 print("Before interpolation: no values for the crossing_index")
     17 print example_series_with_crossing.ix[crossing_index]
---> 18 example_series_with_crossing.interpolate(method='time', inplace=True, limit=1)
     19 print("\nAfter interpolation:")
     20 print example_series_with_crossing.ix[crossing_index]

C:\winpython\WinPython-32bit-2.7.6.2\python-2.7.6\lib\site-packages\pandas\core\generic.pyc in interpolate(self, method, axis, limit, inplace, downcast, **kwargs)
   2304         if axis == 1:
   2305             res = res.T
-> 2306         return res
   2307 
   2308     #----------------------------------------------------------------------

UnboundLocalError: local variable 'res' referenced before assignment
</code>

**Comment by saroele** [comment]
Cleanup operation, ok for you @Ryton?
