### ISSUE TITLE
Transfer units and conversion factors to fluksoapi.py

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#24]
@Ryton included conversion factors, units and other meta-info in the notebook `Demo_WaterGasElekVisualisation`.  It propose to rewrite it slightly and include it in the fluksoapi module in order to avoid code duplication.  

With rewrite slightly, I basically think of using dictionaries instead of lists, and using the utility (gas, water or electricity, later maybe also the variables measured by Kubes) as key.

**Comment by saroele** [comment]
This never made it to the develop branch, I don't know why we 'forgot' it. 
Nevertheless, units are important!

Taking a step back, I have the impression that we tried to reinvent the wheel.  There are good unit libraries in python, and I think pint is one of the most used.  

Also, we have a new houseprint class now, and the Sensor object has attributes for 'type', 'quantity' and 'unit'.  I dont think quanity is needed if we use pint to define the unit.  

So the approach I have in mind: 

* use the unit attribute in each sensor to define what unit the raw source data is in
* apply a unit conversion in the get_data() method of the sensor.  For now, just  simple conversion and differentiation to standard units seems ok as a start. 
* later we can add target units to the get_data() methods and use pint to automatically convert.

**Comment by Ryton** [comment]
Possible Explanation: i never pushed it, as i'm not sure it was solid, both in coding and in value consistency.

I never heard of 'pint' till now, but would love to look into it (if no-one else wants to prioritize this at least)! 

Plan of attack:
* Adding conversion (& Diff) towards SI-units first makes most sense imho.
* Later this can be extended (if needed) with other, more tangible units or with economics, such as [€/ time unit] or [€] .

**Comment by saroele** [comment]
I did a pull request yesterday, I think I made big step forward.  Basically, unit conversion is now in the hear of the Sensor object, and that's a logic place.  I documented and demo'd everything in the notebook Demo_Units_and_Conversion.ipynb in the issue24 branch.  (see here: https://github.com/opengridcc/opengrid/blob/issue24_UnitConventions/notebooks/Demo_Units_and_Conversions.ipynb)

I think that the only thing missing compared to what you did @Ryton is costs and tariffs. For fixed tariffs, its just a multiplication, for day/night or variable tariffs we need to define Timeseries with the cost profile and do an element-wise multiplication.  Maybe this is not a priority now?  I would also do this in a different issue. 

Also, the units are not incorporated in the data itself.  It would be an interesting idea to extend the DataFrame and Series objects with a unit attribute?  That's a new development though, and not high priiority now. 

If you have a look this weekend, start with the Demo notebook and see if that is sufficient for now. Curious to hear your feedback!

**Comment by Ryton** [comment]
Great, it looks like you made lots of progress already! 
Will take a look at it.

PS: I still disagree about the low priority of adding costs & tarrifs though. ;-)
At least adding a fixed tarif is quick to implement & can generate very tangible insights! ;-) 
Though the calculated results may be a bit of compared to the real bill, with the uncertainties on:
* some measurements (missed pulses, scaling error, sensor uncertainty)
* caloric value of high vs low caloric gas 
* (measured) apperent electrical power instead of real (accounted) power.

**Comment by saroele** [comment]
I think the best way is to associate a tariff to a Site.  It will then be available to all Devices and Sensors on this site.  To define a tariff we need:
- the quantity or type (like electricity, gas, water, fuel)
- unit (€/m**3, c€/kWh, €/MWh, ...)
- a cost profile. 
There are different options for the cost profile:
- flat
- weekly profile based on weekday and hour
- any other profile
The first two can be configured with just a few parameters, the latter requires a pandas Series or DataFrame with the profile. I have a method lying around to create a weekly profile, eg for day/night tariff. 

Maybe we can define a small class that defines a tariff.  We can then subclass it for the different options.  A tariff object should have a method to return a dataframe with the cost of a given profile.  Obtaining the price would then be something like: 

    tariff = TariffWeekly(type, unit, cost_low, cost_high, days_high, hours_high)
    power = Sensor.get_data(head=..., tail=...) # returns a df
    cost = tariff.get_cost(power) # a dataframe with cost instead of power

This seems something very generic, and we can then also check the units and raise an exception if the unit of the power dataframe and of the tariff are not compatible.  At this moment however, the `power` dataframe does not contain info about its own cost.  I'd like to add the unit as attribute to the dataframe.

**Comment by saroele** [comment]
Discussion and results from meeting:
- unit can be added to series as attribute and will be preserved when concateing a series to dataframe
- check if slicing the dataframe keeps the unit ==> NO
- so using this attribute is not really a solution: the attribute gets lost when doing .copy() or other operations

Conclusion : fixing the default units of dataframes and series as follows:

The default resulting unit for counter values (diff=False) are:

sensortype      unit

water       ==> liter
gas         ==> kWh
electricity ==> kWh

The default resulting unit for flux values (diff=True) are:

sensortype      unit

water       ==> liter/min
gas         ==> W
electricity ==> W    


About costs and tariffs: lets make another issue and keep it on the list.  Not top priority now.

**Comment by saroele** [comment]
I have made one more useful change: all get_data() methods will return a dataframe with unit attribute set for each column. As we discovered, this is not persistent: pandas will remove this attribute when doing operations with the dataframe.  But for a first check it is extremely useful. 

Also, each sensor now has a new attribute: cumulative.  For fluksosensors, if it is '' or None, it is determined based on the sensortype, and for electricity, gas or water it will be set to True.  This attribute has an important implication: get_data will use it to determine if the data has to be differentiated or not.  You can override this behaviour by setting diff=True or diff=False in the get_data methods.

**Comment by saroele** [comment]
We're done with the units.  About costs and tariffs: lets make another issue and close this one.
