### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed

### ISSUE THREAD

**Issue by michelfripiat** [opengridcc/opengrid#25]
Hey everybody, 

When trying to run the following script:
```
import sys
sys.path.append('C:/Github/opengrid')


from opengrid.library.houseprint import houseprint
import pandas as pd
from datetime import datetime

start = pd.Timestamp(datetime(2017, 1, 1, 00, 00))
end = pd.Timestamp(datetime(2018, 2, 15, 00, 00))


hp = houseprint.Houseprint()
hp.sync_tmpos()
```

I get the following error:

> Connected to pydev debugger (build 172.3968.37)
Opening connection to Houseprint sheet
Opening spreadsheets
Parsing spreadsheets
35 Sites created
36 Devices created
102 sensors created
Houseprint parsing complete
Backend TkAgg is interactive backend. Turning interactive mode on.
Using tmpo database from /data\tmpo\tmpo.sqlite3
  1%|          | 1/102 [00:00<00:12,  8.20it/s]
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Github/opengrid/opengrid/michel_script/test.py", line 14, in <module>
    hp.sync_tmpos()
  File "C:\Github\opengrid\opengrid\library\houseprint\houseprint.py", line 489, in sync_tmpos
    tmpos.sync(sensor.key)
  File "C:\Users\mfr\.virtualenvs\opengrid\lib\site-packages\tmpo\__init__.py", line 154, in wrapper
    raise e
sqlite3.IntegrityError: UNIQUE constraint failed: tmpo.sid, tmpo.rid, tmpo.lvl, tmpo.bid

Process finished with exit code 1

Any idea what I did wrong? :)

**Comment by michelfripiat** [comment]
Probably related to issue : https://github.com/flukso/tmpo-py/issues/20

**Comment by JrtPec** [comment]
First off: Seems like you are running some old code, because the Houseprint module has been moved to [opengrid-dev](https://github.com/opengridcc/opengrid_dev) a few months ago.
But that shouldn't be an issue.

TMPO has a quirk where sometimes data is corrupted and you get this error when syncing. The only solution I've found is to delete data and try to sync again:
```python
hp.tmpos.reset()
hp.sync()
```
or if that doesn't work
```python
hp.tmpos.remove()
hp.init_tmpo()
hp.sync()
```
If you get an error that tmpo doesn't have a method called `reset` or `remove`, don't forget to update tmpo to the latest version.

**Comment by michelfripiat** [comment]
Hey Jan, Thanks for the quick reply.

I switched to opengrid-dev. Thanks for the info.

Here is what I get when I execute each of the line:
![image](https://user-images.githubusercontent.com/19266490/36380522-e0187182-1582-11e8-9dbc-8ce4042b734c.png)

![image](https://user-images.githubusercontent.com/19266490/36380545-f32f1672-1582-11e8-93a6-20b80c1ae495.png)

![image](https://user-images.githubusercontent.com/19266490/36380552-faed4384-1582-11e8-912f-95a483f14f76.png)

![image](https://user-images.githubusercontent.com/19266490/36380561-08afd7e8-1583-11e8-813b-caf950f5edf1.png)

My version of tmpo is 0.2.10

By the way, I run the script on python 2.7.13

**Comment by JrtPec** [comment]
Ah rats, you need to supply the sensorid for it to be reset...

Let's do the sync manually, try this:
```python
from opengrid_dev.library.houseprint import houseprint
import tmpo
from sqlite3 import IntegrityError

hp = houseprint.Houseprint()
tmpos = tmpo.Session()

for sensor in hp.get_fluksosensors():
    tmpos.add(sensor.key, sensor.token)
    try:
        tmpos.sync(sensor.key)
    except IntegrityError:
        tmpos.reset(sensor.key)
        tmpos.sync(sensor.key)

hp.init_tmpo(tmpos=tmpos)
```

**Comment by michelfripiat** [comment]
Great, my tmpo has been updated now! 

By the way, 38 sensors had to be reset and I still get the IntegrityError when executing hp.sync_tmpos():

e8fa1a454e137aa36c1adfd9de94406b
313b78fec4f845be91c328ee2f92c6d4
b28509eb97137e723995838c393d49df
dfb719cc8240de810862228a7d1f37f3
2dd0f6942224767b18a411415f67b423
d4b28740c7ee7a98f94a4d23d794af79
b841eb895810525017ddc5d932d37eb7
1e1e43f5edb4d5e43ab721c391410cde
36dac700f81c6be9ca233e6534182ed4
b325dbc1a0d62c99a50609e919b9ea06
ad322ec64956ed232cb94a72517004ab
1a1dac9c2ac155f95c58bf1d4f4b7d01
7d91f092ae6a01ff3670ac003ea0eadc
2923b75daf93e539e37ce5177c0008c5
565de0a7dc64d8370aa321491217b85f
a7d523e79909ad098bccc337c5da84a0
9afa3357cee100c6a8a5059c63e29295
a8054ca7865584e69a7c946aeea1e13c
fad495c097e2d8f2c041c0f00c553139
56f28789f52236df4647d06111ff515a
ce8ab098fc7479dcb3699f307c8e88a7
d5a747b86224834f745f4c9775d70241
1a5c55ec176d24483572aca420ac59b5
4d23c511766514749bc84e29af6f444e
ba14f92064072f9783baf27f45a147b4
81fb589c911e808daa96a2064bebed41
d209e2bbb35b82b83cc0de5e8b84a4ff
a5c7faf24bf77ccb13f59e5d87731524
c1a78eacaa6a82d3257a278d3e99088a
8520ae493bcc57574e09b6ff7b13be76
2e2e42c92da420eba8fb9aeea78376fc
62597ad3e7b8a543db2a574bf5d4685b
d23028c01bea77170d8d8ee6254a5a2c
214ef2d3533899dbf633caeb32e80483
894589249d671d09a7950cc435bd604c
a519ce042e8748570d3a91cfca16a747
bc991a93831b571ddf5b6e29103b9c9f
ddc0a3bdfaa05e624240dec821411232

**Comment by JrtPec** [comment]
What we did here was just a fancy way of deleting the corrupt data and retrying the sync.

You could also just delete the `tmpo.sqlite3`-file and run the sync again. That way you start from scratch.
You can find out where it is saved in `hp.tmpos.db`

**Comment by michelfripiat** [comment]
For information, I tried to delete all files coming from hp.tmpos.db but didn't help. I still get the same issue.

**Comment by JrtPec** [comment]
Ok, I'm a bit out of ideas... Maybe you could go find @saroele and troubleshoot with him?
