### ISSUE TITLE
Interactive plots

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#27]
@Ryton started experimenting with d3.  Let's use this thread to discuss all options wrt interactive plots, which tools we will use et. 

@Ryton : I will create a new branch for this and remove the notebooks from the develop branch

**Comment by Ryton** [comment]
Yet Another Candidate: 
The Charts python library https://github.com/arnoutaertgeerts/python-highcharts ,
based on Highcharts, created/supported by a colleague!

**Comment by saroele** [comment]
Last meeting Arnout was present, and he convinced us all (rather easily) to use python-highcharts.  So we'll be able to close this thread very shortly.

**Comment by saroele** [comment]
so python-highcharts seems to do the trick.  Let's use it as standard plotting engine as much as possible.   More info: https://github.com/arnoutaertgeerts/python-highcharts
