### ISSUE TITLE
Opengrid website

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#35]
I think we need a URL per fluksometer (can contain the fluksoID I think).  
Then, on that site we want a link for each energy vector: elec, gas, water
Then on the page per vector, we want a page per day?
And on that page we can then just put the graphs for that vector and that day?

**Comment by saroele** [comment]
Flask website is up at http://95.85.34.168:5000/
Next steps: 

* make structure per sensor or per type (electricity, water) and per graph
* add the graphs, as png first?

**Comment by dirkdevriendt** [comment]
*moved to https://github.com/opengridcc/website/issues/5*
