### ISSUE TITLE
Small issues about the MVLR

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/opengrid#43]
Some stuff to discuss during the next meeting:

I've been playing around with the Multivariate Linear Regression and there are some things I think could be improved upon:

* Usage of `kwargs.get(...)` instead of listing the arguments in `__init__`. I don't like it because now I don't get tab completion in a notebook. I get that the code looks cleaner but I don't think it is worth it.
* I get why the analysis isn't run upon initialization, but we should add some explanatory errors. This was my use case: `mvlr = MultiVarLinReg(...); mvlr.plot()`. It threw me: `AttributeError 'MultiVarLinReg' object has no attribute 'fit'`. Took me a while to understand why that was happening. We could fix this by making `fit` a property that tries to return `_fit`, but tells you to run the analysis first if it can't find it.
* The Demo notebook also throws this AttributeError
* There are some Pandas warnings about values be set on slices of DataFrames.

**Comment by saroele** [comment]
thanks for the feedback Jan, I'll improve the function
