### ISSUE TITLE
Plans to standardise houseprint "Function"?

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/opengrid#46]
Are there any plans to introduce some kind of convention to the naming of the Function of a sensor in the houseprint?

It would for instance be nice to filter for only solar panels, or only total meters and no submeters...

**Comment by vi-di** [comment]
This is important! I’m currently looking into this. A nice but not perfect exemple is the opensource project-haystack.org<http://project-haystack.org>. I’m taking the good things out, but it’s totally there yet for renewable sources for instance. We plan a next dev meeting. We can discuss it there. I’ll prepare some thoughts about it. Vincent

Van: Jan Pecinovsky
Beantwoorden - Aan: opengridcc/opengrid
Datum: maandag 23 februari 2015 15:09
Aan: opengridcc/opengrid
Onderwerp: [opengrid] Plans to standardise houseprint "Function"? (#46)


Are there any plans to introduce some kind of convention to the naming of the Function of a sensor in the houseprint?

It would for instance be nice to filter for only solar panels, or only total meters and no submeters...

**Comment by saroele** [comment]
Let's continue the discussion in #54
