### ISSUE TITLE
Carpetplot > 35 days

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/opengrid#47]
I can't make carpet plots that are larger than 35 days.
The output is only `<matplotlib.figure.Figure at 0x11563cc10>`, but no figure. Under 35 days works fine.

When I try to save to file I get `ValueError: No sensible date limit could be found in the AutoDateLocator`

Seems to have something to do with this part from plotting.py:
```
if abs(number_of_days) <= 35:
        ax.yaxis.set_major_locator(DayLocator())
    else:
        ax.yaxis.set_major_locator(AutoDateLocator())
```

**Comment by JrtPec** [comment]
Updating matplotlib from 1.3.1 to 1.4.3 solved the problem.

**Comment by saroele** [comment]
Well found, thanks for letting us know!!
