### ISSUE TITLE
Houseprint metadata?

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/opengrid#49]
Do we have some more metadata for the houses somewhere?
Specifically I'm looking for the living area square meters (bewoonbare oppervlakte) and the number of inhabitants.

**Comment by vi-di** [comment]
Is this not included in the Googlesheet? If this could help, all opengrid members can join EnergieID and become member of the opengrid group (www.energieid.be/groups/opengrid<http://www.energieid.be/groups/opengrid>). By becoming member, all metadata can be shared with opengrid. Square meters and number of inhabitants are standard questions. We also have more info on meters and metertype in combination with their sensorID and token. For this to be usefull, more opengrid people should join this group. We now have only 7 members.

V

From: Jan Pecinovsky
Reply-To: opengridcc/opengrid
Date: donderdag 19 maart 2015 13:42
To: opengridcc/opengrid
Subject: [opengrid] Houseprint metadata? (#49)


Do we have some more metadata for the houses somewhere?
Specifically I'm looking for the living area square meters (bewoonbare oppervlakte) and the number of inhabitants.

**Comment by JrtPec** [comment]
Ok, thanks, found the googlesheet!

So right now the Houseprint code only extracts Flukso names and sensor data? I'll add some methods to extract other metadata then...

**Comment by saroele** [comment]
That's right, there is a lot more info in the houseprint that is not yet extracted.  Would be nice to have these additional info at hand for the scripts!  Thanks for having a look :-)

**Comment by JrtPec** [comment]
I have added two methods to extract number of inhabitants and house size in this commit: https://github.com/JrtPec/opengrid/commit/449752ddd0dd662562becbd91cb741a8571158aa

It's rather clunky though: I save a dictionary of the flukso_id and the property I want in the houseprint object. I have done it for two properties now but in theory you could do this for every column in the google sheet and have a `get_specific_column(flukso_id)` method for every property of the house... Looks like an awful lot of redundant code to me.
There should be an easier way to convert the google sheet into easy accessible data, something to look at in the future.

For now however my issue is solved.

**Comment by saroele** [comment]
Well done.  I can have a look in a few weeks to make it more generic.
tnx
