### ISSUE TITLE
gspread.exceptions.AuthenticationError: Unable to authenticate. 404 code

### ISSUE THREAD

**Issue by ronisegoly** [opengridcc/opengrid#56]
Starting few days ago I get this error on my Python scripts which get and puts data in Google 
I spreadsheet. Till now all worked smooth for long period
I used specific password supplied by Google for a service I crated defined
I think Google made changes but I read the API is not changed.
In any case I am not quite clear it's related issue
Anyone?

**Comment by saroele** [comment]
I think you're in the wrong repo with this question, but nevertheless: we also had gspread warnings about authentication (password authentication is deprecated). We solved it by using the oauth api.  
You can find our solution here: https://github.com/opengridcc/opengrid/blob/develop/library/houseprint.py
