### ISSUE TITLE
New OO Houseprint structure

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/opengrid#58]
So last night there was a lot of talk about restructuring the Houseprint (both the spreadsheet as the python code).

I have written a basic OO architecture (contains a lot of pseudocode):
https://github.com/JrtPec/opengrid/blob/new-houseprint/scripts/New%20Houseprint.ipynb

It would be nice if some of you could check it out and give me your thoughts before I continue with the implementation.

**Comment by saroele** [comment]
Nice!

I had a quick look and this seems the way to go.  I'll spend a bit more time one of these days, but would be good if also others would throw an eye on it.

**Comment by JrtPec** [comment]
@saroele I have committed a full implementation with a demo. It has turned out bigger than expected, but imo. very functional and easy to use.

**Comment by saroele** [comment]
dag Jan,

Nu heb ik het al iets meer bekeken, nog niet genoeg maar ik kan toch al een eerste reactie geven.  En die is: puik werk! 
Dit ziet er zeer functioneel uit, en proper geprogrammeerd.  Als ik streng ben zou ik je nog hetvolgende vragen:
- graag ook docstrings voor de private methods
- unittest? Heb je daar ervaring mee?  Anders help ik die mee opzetten.
- dit steken we best in een module ipv een notebook.  De tutorial mag dan in de notebook blijven. 

En dan moeten we de huidige versie van de houseprint module vervangen door deze, en we hebben weer een mooie stap gezet!  

Ik kan nog wel een paar uur vrijmaken voor ik op vakantie vertrek, het zou fijn zijn als we dit konden afwerken.  Maar alvast: mooi gedaan!

roel
-

**Comment by JrtPec** [comment]
Ik heb mijn branch volledig aangepast aan de nieuwe houseprint structuur:

• Code is in een module gezet. Notebook is enkel nog demo.
• Oude houseprint is verwijderd.
• Alle notebooks zijn aangepast aan de nieuwe houseprint en werken.
• De jobs cache_anonymous_houseprint, job_SyncAndRenderGraphs en job_SyncTmpo zijn ook aangepast aan de nieuwe vorm, moeten wel waarschijnlijk getest worden op de server.

The bad news: CSV is niet meer supported. De jobs die daarvoor zorgden zullen niet meer werken. De module fluksoapi wordt ook niet meer gebruikt en kan eigenlijk ook verwijderd worden.

Mijn volgende stap is een paar unittests aan de praat krijgen. Ik heb daar geen ervaring mee maar ik zal het wel uitzoeken. Wanneer je terug bent van verlof mag je mij daar zeker eens mee helpen.

Daarna begin ik met versie 3 van de houseprint: eentje die compatibel is met de metadata van EnergieID.

**Comment by saroele** [comment]
Hoi Jan,

Klinkt goed! Code bekijken ga ik pas binnen een paar weken doen,  maar ik
heb niet de indruk dat je me dringend nodig hebt ;-)

Voor unittests kan je je altijd inspireren op de eenvoudige tests die ik
had gemaakt voor de vorige versie van houseprint en fluksoapi. En anders
doen we dat in september  wel.

Groetjes uit Griekenland,
Roel
Op 30 jul. 2015 17:54 schreef "Jan Pecinovsky" <notifications@github.com>:

**Comment by saroele** [comment]
FYI: pull request of Jan with the new houseprint is merged in the develop branch. In the coming days, we will still modify the api a little bit, and use the branch issue58_houseprint and this issue 58 to discuss.

**Comment by saroele** [comment]
I did some modifications to the houseprint, most important is the incorporation of the config file. 

Important: from now on, add the path to the opengrid code to PYTHONPATH.  Will also add it to the wiki. 

See also 33fb6cb and a80a39d

**Comment by saroele** [comment]
We now also have a basic unittest for the houseprint, so this issue can be closes.  If there are problems of feature requests for the houseprint, we open a new issue.
