### ISSUE TITLE
tmpo sync error

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#59]
@icarus75 Can you have a look at the error below?  Happens both on my computer and the droplet.  You can probably reproduce with the SynchronizeData.ipynb notebook.

Thanks,
Roel

ValueError                                Traceback (most recent call last)
<ipython-input-6-e0db1674fb8a> in <module>()
----> 1 tmpos.sync()

/mnt/data/work/opengrid/code/tmpo-py/tmpo.pyc in sync(self, *sids)
    176             else:
    177                 rid, lvl, bid = 0, 0, 0
--> 178             self._rqsync(sid, rid, lvl, bid)
    179 
    180     def list(self, *sids):

/mnt/data/work/opengrid/code/tmpo-py/tmpo.pyc in _rqsync(self, sid, rid, lvl, bid)
    273         r = f.result()
    274         fs = []
--> 275         for t in r.json():
    276             fs.append((t,self._rqblock(sid, token, t["rid"], t["lvl"], t["bid"], t["ext"])))
    277         for (t,f) in fs:

/usr/local/lib/python2.7/dist-packages/requests/models.pyc in json(self, **kwargs)
    817                     # used.
    818                     pass
--> 819         return json.loads(self.text, **kwargs)
    820 
    821     @property

/usr/lib/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    336             parse_int is None and parse_float is None and
    337             parse_constant is None and object_pairs_hook is None and not kw):
--> 338         return _default_decoder.decode(s)
    339     if cls is None:
    340         cls = JSONDecoder

/usr/lib/python2.7/json/decoder.pyc in decode(self, s, _w)
    364 
    365         """
--> 366         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    367         end = _w(s, end).end()
    368         if end != len(s):

/usr/lib/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
    382             obj, end = self.scan_once(s, idx)
    383         except StopIteration:
--> 384             raise ValueError("No JSON object could be decoded")
    385         return obj, end

ValueError: No JSON object could be decoded

**Comment by Ryton** [comment]
365 """
--> 384 raise ValueError("No JSON object could be decoded")

It seems the returned json was empty. 
Maybe there is no data for that period, for that sensor? eg a water or gas sensor with no consumption (or loose sensor?)

**Comment by Ryton** [comment]
Yup, its an empty /removed sensor-token combination, for that date.
But still, it would be better if it trows an understandable error, or return an empty time series.

If i enter one of my own sensors/tokens, it works fine.
>in DemoTmpo, this gives an error:
s.add('d209e2bbb35b82b83cc0de5e8b84a4ff','e16d9c9543572906a11649d92f902226')

when i replace sensorname & token, it works fine:
s.add(<sensor name>,<sensor token>
Request block | time:1434652025.389 sid:4d23c511766514749bc84e29af6f444e rid:0 lvl:20 bid:1413480448
Request block | time:1434652025.390 sid:4d23c511766514749bc84e29af6f444e rid:0 lvl:20 bid:1414529024
...

**Comment by saroele** [comment]
But the exception is thrown in a ``tmpo.sync()`` call.  So the cause would be that a sensor did not produce any new information since last ``tmpo.sync()`` call? Seems strange.  

Btw, last sync on the droplet was successful (syncing every hour now).
