### ISSUE TITLE
Weather data and derived metrics

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#6]
We need hourly weather data for 2016 in `opengrid.datasets`.  I propose to add a dataframe with:

- temperature
- relative humidity
- solar radiation (global horizontal, if available also direct normal or diffuse)
- wind speed
- wind direction
- pressure

I think we need a method in our library for computing heating and cooling degree-days from the ambient temperature.

**Comment by JrtPec** [comment]
There are two methods in opengrid_dev > misc, called `calculate_temperature_equivalent` and `calculate_degree_days`, they should have all you need. We can port them to the main opengrid repo.

**Comment by saroele** [comment]
Yep, that's what I'm working on.  A bit struggling with the rename to opengrid_dev: it's not yet adapted in all files.  No worries, I'm looking at it now.
