### ISSUE TITLE
cron does not find ipython

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#60]
Does anyone with more linux knowledge knows how to solve this: when I run an ipython command on the droplet, it works fine.  When I past the same line in the crontab and log the job, I get the following message:

/bin/sh: 1: ipython: not found

I already understood that cron jobs run in a different environment, but how can I get that environment to know ipython?

**Comment by wouterh** [comment]
as a normal user, try:
which ipython
-> this will give you the full path to ipython

Put the full path in the crontab.

**Comment by Ryton** [comment]
Funny bug!  :-D 
i have the exact opposite issue on my laptop...,i can run it as super user (sudo ipython notebook), but not as a normal user:
$ which ipython
/usr/local/bin/ipython
$ ipython
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 9, in <module>
    load_entry_point('ipython==2.2.0', 'console_scripts', 'ipython')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2278, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group,name),))
ImportError: Entry point ('console_scripts', 'ipython') not found

**Comment by dirkdevriendt** [comment]
It seems the standard shell when logging in over SSH is bash, while according to your message crontab jobs are running with sh. So the problem is likely explained by a difference in PATH between the two shell environments.

**Comment by saroele** [comment]
Adding the full path to ipython solved the issue.  Thanks!
