### ISSUE TITLE
syncronise data notebook corrupted

### ISSUE THREAD

**Issue by Ryton** [opengridcc/opengrid#61]
opening http://localhost:8888/notebooks/scripts/SynchronizeData.ipynb
in branch develop trows a Bad request error.

Error message:
2015-06-18 19:56:15.304 [NotebookApp] WARNING | Unreadable Notebook: /home/ryton/opengrid/develop/scripts/SynchronizeData.ipynb global name 'NBFormatError' is not defined
WARNING:tornado.access:400 GET /api/notebooks/scripts/SynchronizeData.ipynb?_=1434650174503 (::1) 3.07ms referer=http://localhost:8888/notebooks/scripts/SynchronizeData.ipynb

I'll try one in another branch, but i read that @saroele added a commit on this recently?

**Comment by Ryton** [comment]
Hmm, probably it's my local installation that's causing the error... 
Some other notebooks in develop give the same result, eg the DemoHouseprint.
While others open /run fine

**Comment by dirkdevriendt** [comment]
You may need do upgrade IPython; the notebook format changed in version 3 and the notebooks are automatically converted to the new format when somebody opens them with the new IPython version.

**Comment by saroele** [comment]
Yes,  you need to update ipython.
Op 18 jun. 2015 20:29 schreef "dirkdevriendt" <notifications@github.com>
het volgende:

**Comment by Ryton** [comment]
Ok thx, will do. Maybe it solves my sudo problem in the mean while ;-)

**Comment by Ryton** [comment]
Updated ipython. Now i know why my colleagues had another window lately :P
Thanks! Works correctly now, thus this can be closed.

Another Q though: the  houseprint.py (called by demohouseprint notebook) expects  a "json" entry in the opengrid.cfg file.
> gjson = c.get('houseprint','json')
I cannot find any reference in the doc/example. What should this be, just a dir, or a string, or ...?
Will dig in the code now to work it out myself, but maybe you're faster ;-)

**Comment by Ryton** [comment]
Ah yes, now i remember, the gdoc login procedure was changed. 
@saroele could you send me this json key plz? 
(not urgent, will continue tomorrow)

**Comment by Ryton** [comment]
or just an anonimized houseprint would do too :-)
