### ISSUE TITLE
TMPO down?

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/opengrid#67]
Anyone else experiencing problems with the TMPO sync? I get no data after about 15/10/2015 19:00. I checked the time series on opengrid.be and it looks like there is no data over there too... @icarus75 ?

**Comment by saroele** [comment]
Same thing here, no data after 15/10/2015 19:00 (UTC).
Must be something in the tmpo server.  @icarus75 ?

**Comment by JrtPec** [comment]
@saroele I got a text from @icarus75 saying that it should be fixed. Everything looks fine on my side, so I'm closing the issue?
