### ISSUE TITLE
easy pip-install config for library

### ISSUE THREAD

**Issue by rubenbaetens** [opengridcc/opengrid#70]
The `opengrid` library uses many python libraries i don't have on my laptop. Making a simple `requirements.txt` including all used python libraries allows to do
```
pip -r requirements.txt
```
installing all required libraries at once in a single command.

**Comment by saroele** [comment]
Sure, a good idea. It's a first step in order to make an opengrid package itself: doing `pip install opengrid` would even be easier!

**Comment by saroele** [comment]
Another step to simplify the installation procedure would be to include the tmpo-py code inside opengrid.  But that is only a bad solution once we know how to package both libraries.  

The the only good solution is to work on packaging, both for tmpo-py and for opengrid.  The aim is that `pip install opengrid` installs all dependencies, and the only thing to do is setting passwords and some paths in the `opengrid.cfg` file.

**Comment by JrtPec** [comment]
I thought about trying `pip install opengrid` again on a virgin Ubuntu machine, but this time using `apt-get install numpy` etc. instead of `pip install numpy` so that you don't need to install compilers and such.

I got as far as

    sudo apt-get update
    sudo apt-get install python-numpy python-pandas python-pip
    sudo pip install opengrid -v

but now I get
```
sudo pip install opengrid -v

Downloading/unpacking opengrid
  Using version 0.2.0 (newest of versions: 0.2.0, 0.1.0)
  Downloading opengrid-0.2.0.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/o/opengrid/opengrid-0.2.0.tar.gz#md5=4fcdf900b61675d471138eced3dd2a8a (from https://pypi.python.org/simple/opengrid/)
  Running setup.py (path:/tmp/pip_build_root/opengrid/setup.py) egg_info for package opengrid
    
    Usage:
      pip install [options] <requirement specifier> ...
      pip install [options] -r <requirements file> ...
      pip install [options] [-e] <vcs project url> ...
      pip install [options] [-e] <local project path> ...
      pip install [options] <archive url/path> ...
    
    no such option: --no-cache
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/opengrid/setup.py", line 25, in <module>
        raise Exception("Could not install dependencies")
    Exception: Could not install dependencies
    Complete output from command python setup.py egg_info:
    

Usage:

  pip install [options] <requirement specifier> ...

  pip install [options] -r <requirements file> ...

  pip install [options] [-e] <vcs project url> ...

  pip install [options] [-e] <local project path> ...

  pip install [options] <archive url/path> ...



no such option: --no-cache

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/opengrid/setup.py", line 25, in <module>

    raise Exception("Could not install dependencies")

Exception: Could not install dependencies

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/opengrid
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/opengrid
```

@saroele any ideas?

**Comment by saroele** [comment]
My first impression is that this is caused by a pip version that's too old.
Try to upgrade pip first: sudo pip install -U pip

**Comment by JrtPec** [comment]
Correct. It worked. I have updated the linux install instructions on the Wiki.

**Comment by dirkdevriendt** [comment]
sorry to re-open, but apt-get is usually behind in version when compared to pip; on a new machine we should be able to use (assuming at least Python 2.7.9, with pip included):

  apt-get build-dep python-numpy
  pip install -U pip
  pip install numpy

note: if you want to get rid of the "sudo pip" and you prefer not to use venv, I think the recommended way is to use:

  pip install --user packagename

**Comment by saroele** [comment]
Updated the wiki and included the suggestions of dirk.
