### ISSUE TITLE
Finalise testing 

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#79]
New thread to discuss our testing infrastructure.  Todo:

* put tests next to code or in separate folder? After all, I may prefer to include the tests next to the source files instead of in a separate folder. It's easier during development to have the code and the test next to each other in the same folder. 
* add code coverage 
* add integration tests based on the notebook folder: run the notebooks and make sure they don't raise exceptions?  Is this a good idea?
* test the tests: what if you have an installed version and the source code?  Using virtualenv?

**Comment by WolfBerwouts** [comment]
Possible topic for the next meeting? Maybe someone can give a small demo of how to make these tests?

**Comment by saroele** [comment]
Yes, good idea.  I worked on testing,  so I can give intro and manage a
discussion about testing,  pull requests and the Travis ci integration.

Thanks,Roel
Op 13 jan. 2016 23:26 schreef "Wolf" <notifications@github.com>:

**Comment by saroele** [comment]
I'm happy to announce that a code coverage check is now included based on www.coveralls.io and a badge is added to our readme page. I will close this issue and merge branch issue76_testing in the develop branch.
