### ISSUE TITLE
Carpetplot raises error in the waterleak detection notebook

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#86]
The notebook runs fine, except for the carpet plots that are made.
@kdebrab , any experience with this bug? 

Here's a stack trace, looks like the most interesting line is majorLocs = self.major.locator()

ValueError                                Traceback (most recent call last)
/usr/local/lib/python2.7/dist-packages/IPython/core/formatters.pyc in __call__(self, obj)
    333                 pass
    334             else:
--> 335                 return printer(obj)
    336             # Finally look for special method names
    337             method = _safe_get_formatter_method(obj, self.print_method)

/usr/local/lib/python2.7/dist-packages/IPython/core/pylabtools.pyc in <lambda>(fig)
    205 
    206     if 'png' in formats:
--> 207         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    208     if 'retina' in formats or 'png2x' in formats:
    209         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

/usr/local/lib/python2.7/dist-packages/IPython/core/pylabtools.pyc in print_figure(fig, fmt, bbox_inches, **kwargs)
    115 
    116     bytes_io = BytesIO()
--> 117     fig.canvas.print_figure(bytes_io, **kw)
    118     data = bytes_io.getvalue()
    119     if fmt == 'svg':

/usr/lib/pymodules/python2.7/matplotlib/backend_bases.pyc in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2165                     orientation=orientation,
   2166                     dryrun=True,
-> 2167                     **kwargs)
   2168                 renderer = self.figure._cachedRenderer
   2169                 bbox_inches = self.figure.get_tightbbox(renderer)

/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.pyc in print_png(self, filename_or_obj, *args, **kwargs)
    503 
    504     def print_png(self, filename_or_obj, *args, **kwargs):
--> 505         FigureCanvasAgg.draw(self)
    506         renderer = self.get_renderer()
    507         original_dpi = renderer.dpi

/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.pyc in draw(self)
    449 
    450         try:
--> 451             self.figure.draw(self.renderer)
    452         finally:
    453             RendererAgg.lock.release()

/usr/lib/pymodules/python2.7/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     53     def draw_wrapper(artist, renderer, *args, **kwargs):
     54         before(artist, renderer)
---> 55         draw(artist, renderer, *args, **kwargs)
     56         after(artist, renderer)
     57 

/usr/lib/pymodules/python2.7/matplotlib/figure.pyc in draw(self, renderer)
   1032         dsu.sort(key=itemgetter(0))
   1033         for zorder, a, func, args in dsu:
-> 1034             func(*args)
   1035 
   1036         renderer.close_group('figure')

/usr/lib/pymodules/python2.7/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     53     def draw_wrapper(artist, renderer, *args, **kwargs):
     54         before(artist, renderer)
---> 55         draw(artist, renderer, *args, **kwargs)
     56         after(artist, renderer)
     57 

/usr/lib/pymodules/python2.7/matplotlib/axes.pyc in draw(self, renderer, inframe)
   2084 
   2085         for zorder, a in dsu:
-> 2086             a.draw(renderer)
   2087 
   2088         renderer.close_group('axes')

/usr/lib/pymodules/python2.7/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     53     def draw_wrapper(artist, renderer, *args, **kwargs):
     54         before(artist, renderer)
---> 55         draw(artist, renderer, *args, **kwargs)
     56         after(artist, renderer)
     57 

/usr/lib/pymodules/python2.7/matplotlib/axis.pyc in draw(self, renderer, *args, **kwargs)
   1089         renderer.open_group(__name__)
   1090 
-> 1091         ticks_to_draw = self._update_ticks(renderer)
   1092         ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
   1093                                                                 renderer)

/usr/lib/pymodules/python2.7/matplotlib/axis.pyc in _update_ticks(self, renderer)
    943 
    944         interval = self.get_view_interval()
--> 945         tick_tups = [t for t in self.iter_ticks()]
    946         if self._smart_bounds:
    947             # handle inverted limits

/usr/lib/pymodules/python2.7/matplotlib/axis.pyc in iter_ticks(self)
    887         Iterate through all of the major and minor ticks.
    888         """
--> 889         majorLocs = self.major.locator()
    890         majorTicks = self.get_major_ticks(len(majorLocs))
    891         self.major.formatter.set_locs(majorLocs)

/usr/lib/pymodules/python2.7/matplotlib/dates.pyc in __call__(self)
    800     def __call__(self):
    801         'Return the locations of the ticks'
--> 802         self.refresh()
    803         return self._locator()
    804 

/usr/lib/pymodules/python2.7/matplotlib/dates.pyc in refresh(self)
    818         'Refresh internal information based on current limits.'
    819         dmin, dmax = self.viewlim_to_dt()
--> 820         self._locator = self.get_locator(dmin, dmax)
    821 
    822     def _get_unit(self):

/usr/lib/pymodules/python2.7/matplotlib/dates.pyc in get_locator(self, dmin, dmax)
    894             break
    895         else:
--> 896             raise ValueError('No sensible date limit could be found in the '
    897                              'AutoDateLocator.')
    898 

ValueError: No sensible date limit could be found in the AutoDateLocator.

**Comment by JrtPec** [comment]
I think this is the same issue as https://github.com/opengridcc/opengrid/issues/47

**Comment by saroele** [comment]
Aha, goed punt.  Ik heb idd matplotlib 1.3.1.  Ik probeer te upgraden en test opnieuw. 

bedankt!
