### ISSUE TITLE
de pot

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#90]
was nog geen zotte suggestie om een issue te maken met de stand van de pot...
18 euro, 13 bij mij en 5 bij david

+5 bij mij
:-D

**Comment by WolfBerwouts** [comment]
Haha nerds! :D

2016-01-13 18:28 GMT+01:00 saroele <notifications@github.com>:

**Comment by JrtPec** [comment]
Ha, ik was nog op zoek naar een veldje 'demodata' om SQLAlchemy (#91) mee te testen... misschien kan de pot daar voor dienen ;-)

**Comment by saroele** [comment]
We hebben gisteren mijn deel van de pot opgedronken, dus er is enkel nog 5 euro bij david

@JrtPec: uw pintjes zijn betaald

**Comment by JrtPec** [comment]
Ik sta dus pizza en pintjes in de schuld, we zullen het volgende keer oplossen.

**Comment by WolfBerwouts** [comment]
opgelost? ;)

**Comment by saroele** [comment]
Er is geen pot meer, maar @JrtPec  moet me die pizza nog en @rubenbaetens  moet me een chili-sin-carne :-).  Niet nodig om de issue open te houden...
