### ISSUE TITLE
Abstract Analysis Class

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/opengrid#94]
I was looking at `analysis.py`, where analysis functions are defined as functions that should take a dataframe as input and a dataframe as output.

I would like to suggest adapting this from a function to a class, where we would have an abstract `Analysis` class where all other analyses should inherit from. It would still have to take a dataframe in it's constructor, and would have to implement a `to_df()` function, which would give it the same functionality as the analysis function does now.

There are however added advantages to this approach:
• By using an abstract class, we effectively 'force' developers to implement certain functions and parameters, therefore ensuring that we can visualise them on the website, use them in subsequent analyses, or simply predict their behaviour.
• We can add different 'export functions' to an analysis. Next to a dataframe you could be getting a `to_json()`, `to_img()`, ...
• You could build a more advanced analysis by simply extending upon an already existing one.
• You could easily debug and demo how a certain analysis works 'under the hood' by calling sub-methods

**Comment by wouterh** [comment]
:+1: on good software engineering practices :-)

**Comment by saroele** [comment]
:+1: 
An additional advantage is that it will get easier to write unittests.  We can create a unittest template for all children of the `Analysis` class.  

In order to group the issues and organise us around some 'sprints' as ruben proposed, let's park this for after the website update and start with a discussion on a dev meeting.
