### ISSUE TITLE
cron jobs on droplet don't work

### ISSUE THREAD

**Issue by Ryton** [opengridcc/opengrid#95]
At the moment,  only sensor-data between 2nd and 8th of december is shown on the flask website (both in time series & horizontal benchmark).  The vertical benchmark is done for the date 15/12.

I assume this are the dates when the script was ran last time. Is it planned/possible to add it (again) to a cron job?

**Comment by saroele** [comment]
Yep, the scripts are indeed down due to some changes in code structure etc.  It's my ambition to get them operational again by next tuesday when we have our next meeting.

**Comment by Ryton** [comment]
oki, thought so, but just wanted to bring it to your attention, in case you didn't knew yet.

**Comment by saroele** [comment]
let's keep it open joachim, I'll close it when things work again.

**Comment by Ryton** [comment]
oki, fine by me. Just wanted to keep the list as short as possible ;-)

**Comment by saroele** [comment]
Everything is supposed to work again.  I'll check tomorrow if the cron jobs are fine.

**Comment by saroele** [comment]
Things run for a few days in a row, seems to be ok again.

**Comment by saroele** [comment]
I think the jobs are still working?  Can you specify what's not working?

**Comment by Ryton** [comment]
Hey,

When i open any "SMART MAIN" graph on the site, i get empty charts with "Invalid date" as date range... I doubt this is the wanted configuration?

The normal graphs look flawless. Can these 'smart main' ones be kicked out, or linked to the electricity/gas graph page?

**Comment by saroele** [comment]
ok, I see what you mean.  We'll probably  have to do more severe checks on the sensors and the data availability.  

> The normal graphs look flawless. 

And we even didn't work on making them look nice ... :-D

**Comment by Ryton** [comment]
Impressive sprint results were made, in just one dev-meeting! :+1: 

(maybe split this of to another topic)
Could it be that the charts are 1 hour off? 
A peak at a certain hour on the flukso site (and in reality), is shown as a peak 1 hour earlier in the timeseries and night consumption graphs.

**Comment by saroele** [comment]
Yes, charts are in UTC.  That's a very good point, we have to put them in local time.  I make a separate issue for this

**Comment by Ryton** [comment]
Ok. This one can be closed, then!
