### ISSUE TITLE
[Houseprint] Create db.conn.close method and re-init

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/opengrid#99]
Need to add some methods to disconnect the tmpo sqlite and reconnect it. This to circumvent the "database is locked" errors. Methods are needed for continuous or long running processes so they don't keep the database locked when they are done with it.

**Comment by JrtPec** [comment]
Could we equip the `get_data` method in a `fluksosensor` with something like a setup and teardown for the tmpo database? I hope this will not add even more overhead.

**Comment by saroele** [comment]
I think this should be implemented in tmpo-py. Seems feasible, maybe something for next dev meeting, cause it's also causing me headaches.
